### ISSUE TITLE
Add Champomy for IE team

### ISSUE THREAD

**Issue by Ichimizu** [SoftEng-HEIGVD/Teaching-HEIGVD-RES-2019-Chill#522]

**Comment by Ichimizu** [comment]
IE team is bored to be drunk every thursday so I'm adding Champomy asap

**Comment by wasadigi** [comment]
Cc: @edri

**Comment by edri** [comment]
@wasadigi if you mix Champomy with vodka you'll get a pretty good cocktail tbh
